name: linux-commands

on: [pull_request]

jobs:
  run-linux-command:
    runs-on: ubuntu-latest
    steps:
      - name: install-outlook 
        run: |
          sudo snap install prospect-mail
       