name: android

on : [pull_request_review]

jobs:
  run_window_command:
    runs-on: ubuntu-latest
    steps:
      - name: directory powershell
        run: pwd
      - name: Dirctory Bash
        run: pwd
        shell: bash        