name: android

on : [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: android
        run: |
          import outlook
          shell:android
      - name: python
        run: |
          import platform
          print
          (platform.processor())
          shell: python