name: action-checkout

on : [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: files
        run: |
         pwd
         ls -a 
      - name: cheackout
        uses: actions/checkout@master
      - name: list files again
        run: |
          pwd 
          ls -a

  
        