name: artifact 2

on: [pull_request]

jobs:
  example-job:
    runs-on: ubuntu-latest
    name: art
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file