name: artifacts

on: [push]
jobs:
  example:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      
      - name: Upload output file
        uses: actions/upload-artifact@v3
    
      - name: steps_succed
        if: ${{ failure()}}