name: shell-commands

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "hello world.."
      - name: mulitiline script
        run: |
          node -v
          npm -v
          